// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5MhEyjBk1WapzFuETtDnvhBiB3hmolV0',
    appId: '1:1090470207522:web:00f5b154354813cc7b2a7b',
    messagingSenderId: '1090470207522',
    projectId: 'omsforchatchef',
    authDomain: 'omsforchatchef.firebaseapp.com',
    storageBucket: 'omsforchatchef.appspot.com',
    measurementId: 'G-TNQ2BDGX4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAk9-HSLyEhjgPI1-cPrgq6iZhz2TTtk00",
    appId: '1:290554369819:android:1bf9a12da7d52b1a31a5be',
    messagingSenderId: '290554369819',
    projectId: 'chatchef-391108',
    storageBucket: "chatchef-391108.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgcFkd2M8smg8wHi9SgZf9ijecxAnSxM',
    appId: '1:1090470207522:ios:0087e2654fd28a567b2a7b',
    messagingSenderId: '1090470207522',
    projectId: 'omsforchatchef',
    storageBucket: 'omsforchatchef.appspot.com',
    iosBundleId: 'com.example.oms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtgcFkd2M8smg8wHi9SgZf9ijecxAnSxM',
    appId: '1:1090470207522:ios:0087e2654fd28a567b2a7b',
    messagingSenderId: '1090470207522',
    projectId: 'omsforchatchef',
    storageBucket: 'omsforchatchef.appspot.com',
    iosBundleId: 'com.example.oms',
  );
}
